export const MAP_OBSTACLES = {
  houses: [
    { x: -20, z: -20, radius: 2.5 },
    { x: 20, z: -20, radius: 2.5 },
    { x: -20, z: 20, radius: 2.0 },
    { x: 25, z: 15, radius: 2.0 }
  ],
  walls: []
};

export const GAME_CONFIG = {
  WORLD_SIZE: 100,
  PLAYER_SPEED: 8,
  PLAYER_RADIUS: 0.5,
  CAMERA_DISTANCE: 4.5,
  CAMERA_HEIGHT: 2.2,
  CAMERA_OFFSET_RIGHT: 2.2,
  MOUSE_SENSITIVITY: 0.002,
  TOUCH_SENSITIVITY: 0.005,
  GAMEPAD_SENSITIVITY: 0.004,
  GAMEPAD_LOOK_SPEED: 2.0,
  JOYSTICK_DEADZONE: 0.1,
  NETWORK_TICK_RATE: 30,
  SERVER_PORT: 8765,

  PLAYER_MAX_HP: 100,
  SNOWBALL_DAMAGE: 10,
  SNOWBALL_HEADSHOT_DAMAGE: 25,
  CHARGED_SNOWBALL_DAMAGE: 15,
  CHARGED_SNOWBALL_HEADSHOT_DAMAGE: 40,
  CHARGED_KNOCKBACK_DISTANCE: 2,
  HEAD_HIT_Y: 1.4,

  GRID_CELL_SIZE: 1,
  MAX_SNOW_UNIT: 24,
  SNOW_RECOVERY_RATE: 1,
  SNOW_RECOVERY_INTERVAL: 3,

  SNOWBALL_COST: 3,
  HEAL_PER_SNOWBALL: 2,
  GATHER_DURATION: 2.0,
  MIN_GATHER_DURATION: 0.8,
  GATHER_SPEEDUP_THRESHOLD: 5,
  GATHER_SPEEDUP_PER_BALL: 0.1,
  MAX_SNOWBALLS: 20,

  SNOW_THRESHOLD_FULL: 12,
  SNOW_THRESHOLD_HALF: 6,
  SNOW_THRESHOLD_SPARSE: 1,

  COLOR_SNOW_FULL: 0xffffff,
  COLOR_SNOW_HALF: 0xd4d4e0,
  COLOR_SNOW_SPARSE: 0xa8a8b8,
  COLOR_DIRT: 0x8B7355,

  THROW_SPEED: 15,
  THROW_GRAVITY: 20,
  THROW_CHARGE_TIME: 1.5,
  THROW_CHARGED_SPEED_MULTIPLIER: 2.0,
  THROW_TRAIL_LIFETIME: 0.3,
  THROW_SNOW_GROUND_BONUS: 3,
  THROW_SNOWBALL_RADIUS: 0.15,

  WALL_COUNT: 20,
  WALL_WIDTH: 4,
  WALL_HEIGHT: 1.5,
  WALL_THICKNESS: 0.5,
  WALL_MAX_SNOW_UNIT: 50,
  WALL_SNOW_RECOVERY_RATE: 0.5,
  WALL_GATHER_RANGE: 2,
  WALL_MIN_GAP: 4,

  TALL_WALL_HP: 50,
  TALL_WALL_HEIGHT: 2.25,
  TALL_WALL_WIDTH: 3,
  TALL_WALL_THICKNESS: 0.5,
  TALL_WALL_BUILD_COST: 50,
  TALL_WALL_BUILD_DISTANCE: 2.5
};

export const MESSAGE_TYPES = {
  PLAYER_JOIN: 'player_join',
  PLAYER_LEAVE: 'player_leave',
  PLAYER_MOVE: 'player_move',
  WORLD_STATE: 'world_state',
  WELCOME: 'welcome',
  PLAYER_NAME_UPDATE: 'player_name_update'
};

export const COLORS = {
  SNOW: 0xffffff,
  SNOW_HOUSE: 0xf0f0ff,
  TREE_TRUNK: 0x8B4513,
  TREE_LEAVES: 0x228B22,
  GROUND: 0xe8e8f0,
  SKY: 0x87CEEB,
  CARROT: 0xff6600,
  COAL: 0x1a1a1a,
  WALL: 0xe0e8f0,
  WALL_SNOW: 0xf5f5ff,
  TALL_WALL: 0xb8c8d8,
  CORE: 0xff2222
};
